"""Original, fictional transaction instruments, not licensed forms or legal advice.

Bodies, rendering, and accessible text share this source. No production document,
signature, bank instruction, official certification, or third-party logo is copied.
See docs/document-research.md for inspected examples and limitations.
"""
from __future__ import annotations

from hashlib import sha256

# These are operative provisions/entries, not instructions to an extraction model.
# Repetition within a family reflects related instruments; each instrument also has
# its own completed entries, organization, and execution state.
FAMILY_TERMS = {
    "contract": [
        ("Notices and delivery", "Notices shall be delivered to the receiving party through the representative designated in the agency record, with a copy to the escrow officer when money, dates, title instructions, or possession are affected. A courtesy telephone call does not replace a written notice. Electronic delivery shall include the entire attachment and all referenced continuations; an acknowledgment of receipt does not signify agreement to a proposed change. The sending representative shall retain the transmission time and the receiving address in the correspondence log. A corrected attachment shall identify the earlier attachment it replaces. Statements made during a showing are not incorporated unless reduced to writing and accepted by the parties."),
        ("Included property and condition", "Existing attached lighting, curtain rods, built-in cooking appliances, garage-door opener and two remotes, fixed bathroom mirrors, planted landscaping, and installed irrigation controls are included without separate allocation of price. Seller's freestanding office shelving and movable patio furniture are excluded. Seller shall not substitute an appliance of lesser capacity between inspection and delivery of possession. Manuals and transferable service records in Seller's possession shall be left in the kitchen drawer. No representation is made that a manufacturer's warranty is transferable. Ordinary wear occurring during reasonable residential occupancy is distinguished from a new casualty or the removal of an included fixture."),
        ("Investigation and changes", "Buyer may arrange non-destructive investigations through insured providers with reasonable advance notice. Utilities shall remain available for scheduled inspections, except during an emergency or an interruption outside Seller's control. Intrusive testing, opening walls, and removal of finishes require separate written permission. A request for repairs is a proposal and does not itself amend the price or extend a deadline. Any accepted credit shall identify the amount, purpose, and affected settlement entry. Except for the particular term expressly changed by a signed amendment, provisions of the underlying instrument remain as written. Conflicting instructions shall be referred to the parties before the affected act is performed."),
        ("Performance and settlement", "Delivery of keys shall follow the possession provision, not merely the signing appointment. Escrow shall obtain lender and title instructions applicable to its own work before disbursement. Prorations shown before close are estimates subject to the final settlement calculation; a later corrected tax bill shall be handled as the parties' written instructions provide. A returned document with an omitted initial, incomplete attachment, or unaccepted alteration shall be returned for correction without treating the incomplete entry as consent. Each signatory shall receive a complete counterpart, including incorporated schedules. No representative is authorized by this instrument alone to sign another person's name or change a financing condition."),
    ],
    "lender": [
        ("Applicant correspondence", "Please send documents through the lender's secure intake channel and place the application reference on each attachment. Provide every page of an account statement, including a page containing only disclosures, because running balances and ownership information may appear outside the transaction listing. A large transfer between accounts should be accompanied by both sides of the transfer. Do not redact the account holder's name, statement period, or last four digits needed for matching; full account numbers are not reproduced in this copy. Gifts, borrowed funds, and proceeds from an asset sale have different supporting-document requirements. Contact the assigned processor before substituting one source of funds for another."),
        ("Changes before funding", "Tell the loan officer promptly about a change of employment, compensation structure, occupancy intention, other financed property, new installment obligation, or a changed purchase agreement. A credit inquiry may require an explanation even if no account was opened. Do not assume that a verbal rate discussion is a rate lock or that a lock remains in effect after its stated expiration. An approved program is not permission to disburse against an incomplete settlement file. The lender's closing desk will compare the final contract, hazard evidence, title instructions, and signed package to the conditions applicable at the time it releases funds."),
        ("Amounts and timing", "Escrow deposits and annual premiums are different from the monthly payment retained in a servicing account. A payment illustration excludes utilities, maintenance, and assessments not collected by the lender. Daily interest changes with the actual funding date; the estimate assumes the proposed schedule rather than guaranteeing it. Charges paid before closing should be credited only once. If an invoice changes, retain both the original estimate and the revised amount with an explanation of the affected line. Receipt of this correspondence acknowledges delivery only and does not commit the applicant to a loan. Questions about a specific fee should identify its line code and the version being compared."),
    ],
    "disclosure": [
        ("Seller's continuation — prior work", "During the first winter after purchase, wind-driven rain reached the interior sill of the rear bedroom window. A glazing contractor renewed the exterior seal in April 2021. Seller observed no recurrence during subsequent ordinary rain but did not open the wall cavity or obtain a mold assessment. In June 2023 a plumbing contractor replaced the kitchen faucet and flexible supply connectors; no relocation of a drain or supply line was included. The service invoices are identified in the repair index as R-04 and R-09. The seller does not possess drawings for the original construction and cannot identify concealed piping materials throughout the residence."),
        ("Knowledge limits and records delivered", "Responses concern the seller's actual recollection during occupancy and are not a representation that an unobserved condition cannot exist. A response of 'not known' is different from a negative test result. Roof surfaces, foundation cavities, underground lines, and areas behind stored belongings have not been opened for purposes of these responses. Service papers delivered with the packet are identified by date rather than adopted as the seller's independent expert opinion. Buyer may ask follow-up questions through the representatives and may employ qualified specialists within the investigation arrangements. Later knowledge of a material change shall be conveyed in a dated supplement identifying the earlier response affected."),
        ("Receipt and attachments", "The recipient is asked to compare the subject address on the cover with the property under contract before acknowledging receipt. Receipt does not signify that every question has been answered to the recipient's satisfaction or that any investigation right has been waived. Continuations referenced by a response form part of the delivered record; an unattached reference should be requested before relying on the response. Estimates of age or cost are identified as recollections unless supported by an invoice. Neither a checked response nor the absence of a comment determines insurability, permitted use, market value, or the condition of another component not addressed in that response."),
    ],
    "inspection": [
        ("Conditions at visit", "Access was arranged through the listing representative for the morning appointment. The residence was occupied, furnished, and served by operating water and electricity. Storage along the west garage wall prevented examination of the lower portion of that wall. Furniture and personal effects were not moved. Weather was dry following several days without measurable rain; an absence of active leakage under those conditions does not establish performance during a storm. Photographs referenced by observation number identify the location of a visible condition and are not a comprehensive photographic inventory. Detached furnishings and personal appliances were outside the assignment."),
        ("Methods and inaccessible areas", "Observations were made from normally accessible floors, exterior grade, and the attic hatch where safe. No finish was removed and no destructive test was performed. A readily accessible switch or faucet was operated once; equipment was not dismantled or subjected to a prolonged load test. The inspector did not survey property lines, measure structural capacity, verify an underground pipe route, or determine code compliance. An item described as serviceable means that the limited operation described was observed, not that its remaining service life was determined. A specialist's evaluation may use additional instruments or access not available during this visit."),
        ("Follow-up register", "Keep a repair invoice with the observation number to which it relates, the contractor's scope, and the completion date. An invoice for a single component does not close unrelated observations in the same room. Where a component was inaccessible, later access should be documented before anyone treats that component as examined. Any repair request transmitted by the buyer is separate from this report and requires the parties' written agreement to change the transaction. Reinspection, if ordered, is limited to the stated repaired items and should not be described as a new inspection of the whole property. These observations are not an authorization to enter after possession has transferred."),
    ],
    "settlement": [
        ("Instructions to settlement desk", "Use the file reference on correspondence and preserve the date of each revised instruction. An unsigned email requesting a different payee, beneficiary, or mailing address must be verified under the established call-back procedure before the affected entry is changed. The preparer shall distinguish estimated figures from received funds and distinguish a payoff request from an accepted payoff demand. A preliminary ledger entry is not proof of a bank credit. The escrow officer shall obtain written clarification when instructions from the parties and the lender are inconsistent; no party's silence is to be entered as agreement to a changed amount."),
        ("Reconciliation and retained copies", "Compare the legal description furnished for deed preparation with the title file rather than relying solely on a street address. A corrected spelling or middle initial shall be traced to the person's identification and the vesting instruction. Taxes and prepaid charges may be prorated using different periods; the period and method should accompany the line rather than appear as an unexplained adjustment. Preserve the prior estimate when a charge is updated so that a duplicate debit or credit can be detected. Copies marked 'received' show custody of a document; only the issuing professional can confirm the approval or release that the document purports to record."),
        ("Exceptions and delivery", "Instructions requiring a release, certificate, or third-party consent remain distinct from the actual evidence supplied in response. An exception may be resolved by written commitment from the appropriate party only where acceptable to the title and settlement professionals. Mailing a signed document does not establish recording; preserve the recorder's confirmation separately. Deliver final copies to the named recipients after completion of the applicable step. No account routing number appears in this counterpart. Requests for payment instructions shall be answered through the verified escrow channel rather than by forwarding a previous message containing banking information."),
    ],
    "insurance": [
        ("Conditions and limitations", "Coverage descriptions are subject to the identified policy and endorsements. Replacement-cost terminology does not mean that every kind of loss or every item of property is covered. Deductibles apply to covered losses under the applicable section and may differ for a separately insured peril. Flood, earth movement, wear, neglect, and excluded business activities should not be assumed to be included merely because the building is insured. The agent has not made a flood-elevation survey or determined structural adequacy. Questions about a particular exposure should identify the location, intended use, and relevant endorsement so that the insurer can respond in writing."),
        ("Evidence supplied to lender", "Compare the named insured, location, effective date, mortgagee wording, dwelling limit, and deductible with the lender's request. A quotation is not a binder, and a premium calculation alone does not establish that payment has been received. A later policy may contain endorsements that were not reproduced in the evidence copy. Notify the issuing agent if possession, occupancy, construction activity, or closing date changes before the intended effective date. A requested correction shall identify the particular field being replaced rather than asking the settlement desk to infer a change from another attachment."),
        ("Renewal and claims correspondence", "Maintain an independent contact for the issuing agency and retain the acknowledgment of any change request. Do not send sensitive payment information through an unverified reply address. A claim should identify when the condition was first observed, photographs available, and steps taken to prevent additional damage; this worksheet does not decide whether a future claim will be paid. Estimated annual cost may change at renewal and is not a promise of continued availability. Optional coverages declined at application may be requested later subject to underwriting and the insurer's own effective-date requirements."),
    ],
}

# Unique record-specific entries. The formatting conventions are intentionally
# heterogeneous: numbered contract clauses, letters, schedules, Q/A and reports.
PROFILES = {
    "Purchase Agreement": ("contract", "agreement", [
        ("1. Parties and subject premises", "The undersigned residential purchase agreement identifies {buyer} as buyer and {seller} as seller for {address}, California, APN {apn}. The conveyance includes the appurtenant rights described in the title schedule, subject to the exceptions accepted in writing. The street description is for identification and is not a survey. Buyer intends principal-residence occupancy; no assignment to a different purchaser is authorized by this paragraph."),
        ("2. Consideration and initial delivery", "Purchase price {price}; earnest-money deposit {deposit}; conventional financing. Buyer shall arrange delivery of the initial deposit within the period stated below. The balance of the price, after credit for confirmed deposit and lender proceeds, shall be delivered through escrow. An anticipated receipt is not treated as a posted credit until the escrow holder confirms it. No seller financing, seller repair allowance, furniture allocation, or separate personal-property price is included in the stated consideration."),
        ("3. Schedule incorporated by reference", "Offer date: August 18, 2026. Initial deposit due: August 21, 2026. Inspection period ends: August 29, 2026. Appraisal review date: September 3, 2026. Loan contingency date: September 5, 2026. Disclosure review date: September 7, 2026. Anticipated walk-through: September 14, 2026. Close of escrow: {closing}, subject to subsequent written amendment. A calendar entry or inspection booking does not constitute removal of a contingency; the applicable signed notice must identify the right being removed."),
    ]),
    "Amendment #1": ("contract", "amendment", [
        ("Instrument amended", "Reference is made to the residential agreement dated August 18, 2026 between {buyer} and {seller}, concerning {address}. This continuation addresses the calendar provision only. Escrow reference: {escrow}. The parties' representatives shall circulate this instrument with the underlying agreement rather than extracting its date into a stand-alone instruction."),
        ("Substitution in calendar provision", "The controlling closing date to {closing} is the date entered for the closing milestone. No purchase-price, party, deposit, financing, title, or disclosure term is changed. No additional seller credit, rent-back, assignment, or release of a separate contingency is authorized. The walk-through appointment remains a planning entry subject to access coordination. A financing extension, if needed, shall be requested from the lender separately."),
        ("Counterparts and scope of consent", "The parties' consent to a calendar change does not establish execution of an omitted signature on the underlying contract. An unaccepted negotiation remains unaccepted. A copy shall be supplied to the lender processor and the escrow officer so that their own date-sensitive documents can be reviewed. All pages attached at transmission must accompany the returned counterpart. Initials on this page apply to this amendment and are not to be placed on a different instrument by the recipient."),
    ]),
    "Counteroffer": ("contract", "counteroffer", [
        ("Seller's proposed substitution — clause 2", "Counteroffer states purchase price $910,000. This proposal concerns {address}, escrow {escrow}, and is tendered to {buyer} for written acceptance. Deposit and loan figures in the earlier offer have not been recalculated in this instrument. The recipient shall not assume that the earlier percentage calculations establish the final dollar amounts if this proposal is accepted."),
        ("Return and acceptance record", "Transmitted August 19, 2026 at 14:10 by the listing representative. Requested return: August 20, 2026 at 17:00. Seller proposal signature appears below; buyer acceptance has not been returned in the retained counterpart. No superseding amendment resolves the difference between the $925,000 purchase agreement and this counteroffer. A transmission acknowledgment is retained, but it is not an acceptance of the economic term."),
        ("Reserved terms", "No repair credit, furniture purchase, change of possession, or extension of an inspection deadline is included in this proposal. If an acceptance is returned with an alteration, the alteration must be presented to the other party as a new proposal. The escrow copy is for coordination only until the parties determine the accepted sequence. No officer is instructed to replace the consideration on a deed, loan application, or settlement statement merely upon receipt of this negotiation copy."),
    ]),
    "Escrow Instructions": ("settlement", "instructions", [
        ("Opening instruction 01", "Escrow file {escrow} is opened with Harborfield Title & Escrow for {buyer} and {seller}, property {address}. Casey Morgan is assigned as escrow officer. Written instructions require escrow to hold funds, coordinate prorations, obtain lender funding confirmation, and confirm recording. Proposed consideration is {price}; proposed close is {closing}. These entries are to be checked against the parties' accepted instruments before settlement."),
        ("Instruction 02 — custody ledger", "Identify the remitter, the file to be credited, amount actually posted, and receipt date for each deposit. Do not backdate a receipt to the date a buyer requested a transfer. A pending credit shall be separately marked and shall not reduce the amount still required from the buyer as though received. The deposit requirement appearing in the agreement is {deposit}. Preserve a returned or corrected transfer separately from the original remittance entry."),
        ("Instruction 03 — proration basis", "Use actual calendar days in the applicable period for preliminary property-tax prorations, subject to the final bill and approved instructions. No association dues are entered in this estimate. Utilities remain the parties' direct responsibility unless an agreed settlement charge is supplied. Do not create a tax exemption, payoff credit, or withholding determination from an unsigned worksheet. Release keys only under the written possession arrangement after the required confirmation."),
    ]),
    "Deposit Receipt": ("settlement", "receipt", [
        ("Remittance advice", "File {escrow}; remitter {buyer}; property {address}. Purpose: initial earnest-money deposit under the August 18 agreement. Requested deposit: {deposit}. Delivery reference supplied by buyer: DEMO-DEL-{id}-0821. This reference identifies the buyer's instruction, not an escrow bank transaction. The settlement ledger distinguishes funds requested, funds in transit, and funds posted; only the last category produces a final receipt."),
        ("Cash desk reconciliation", "{receipt_status} The intended credit is toward the buyer's purchase consideration and is not a lender fee or additional charge. The clerk shall compare the originating name with the remitter before applying the amount to the file. A discrepancy in the remitter's spelling shall be documented without creating a second receipt. No interest allocation has been entered in this advice."),
        ("Handling memorandum", "The copy delivered to the buyer representative contains no account or routing number. A returned transfer shall reverse the original ledger credit with a linked entry rather than deleting its history. Additional funds requested before closing require separate verified instructions. This advice does not establish availability of the buyer's remaining cash or authorize an outgoing payment. Questions about posting shall be addressed to the assigned escrow officer using the existing contact record."),
    ]),
    "Agency Disclosure": ("contract", "relationship", [
        ("Representation election", "Buyer representation disclosure identifies Doorlight Demo Brokerage and Avery Chen as the buyer-side representative for {buyer}. Rowan Price is identified as the listing representative for {seller}. The relationship entered here is separate representation; no dual-agency consent is entered. Property under discussion: {address}. Buyer and brokerage acknowledgments are present. Compensation is addressed in the separate buyer service agreement, not established by this acknowledgment."),
        ("Communications and confidentiality", "The buyer representative shall present the buyer's inquiries and written proposals through the transaction channel and shall not represent that the seller has accepted a term without written evidence. Confidential bargaining information shall not be disclosed without appropriate authority. The buyer is encouraged to ask about the source of a factual statement and to distinguish the representative's observation from information supplied by the seller, lender, inspector, or public record."),
        ("Professional assistance", "The client may retain independent legal, tax, lending, insurance, title, survey, or engineering assistance. A broker's coordination of an appointment is not a warranty of the service provider's work. A signature acknowledging this relationship does not waive a contingency or approve a charge. If the representation arrangement changes, the new disclosure and any required consent shall be supplied before proceeding under the changed relationship."),
    ]),
    "Commission Agreement": ("contract", "service-agreement", [
        ("Service period and scope", "Doorlight Demo Brokerage is engaged by {buyer} for the identified acquisition at {address}. This fictional property-specific service record begins August 18, 2026 and ends September 30, 2026 unless ended or extended by written agreement. Services include arranging access, presenting proposals, coordinating retained documents, and communicating transaction dates. Compensation is negotiated between the parties; no rate is described as fixed by law or by a trade association."),
        ("Compensation schedule", "The agreed gross calculation is 2.5 percent of the accepted purchase price, not an additional allocation to personal property. At the reference price {price}, the illustrative gross amount is {commission}. Internal allocation: 80 percent agent and 20 percent broker before the stated $495 fee. That internal allocation is not a second fee charged to the buyer. Credit any compensation actually received from another agreed source against the amount otherwise payable for the same service; do not count a proposed concession as received."),
        ("Billing and authority", "The parties shall identify the accepted price and any permitted third-party payment before preparing a final compensation instruction. No commission is calculated in this record from an unaccepted counteroffer. Disputed charges shall be referred to the brokerage before disbursement. The calculation does not authorize a debit, invoice delivery, external accounting entry, or automatic payment by Doorlight's software. The engagement does not include legal representation, loan underwriting, appraisal, or structural inspection."),
    ]),
    "Financing Approval": ("lender", "letter", [
        ("To Taylor Morgan — underwriting decision", "Re: application HCL-{id}; {address}. Harbor Community Lending has reviewed the conventional owner-occupied, 30-year fixed application with a loan amount of {loan}. Final lender approval and clear-to-close confirmation are retained. The approval entry was issued August 28, 2026 at 11:40 by Morgan Lee, closing desk. Contract, appraisal, insurance evidence, and borrower identity were matched to this application."),
        ("Closing desk entries", "Income and employment review: accepted August 25. Asset sourcing: accepted August 26. Appraisal review: accepted August 27. Hazard evidence: accepted August 28. Title instruction review: accepted for closing-desk preparation. No open borrower-document condition is listed on this decision. Signing, funding, and recording remain subsequent events; this letter is not a receipt for funds or evidence that a deed has been recorded."),
        ("Delivery instruction", "Please coordinate the signing appointment with Casey Morgan using file {escrow}. Advise the closing desk of a proposed change from {closing} before revised interest or insurance dates are entered. An updated employment or credit finding may require reconsideration before release. The approved principal is not the borrower's entire cash-to-close obligation. Refer to the dated settlement figures for deposits, prepaid items, and closing charges."),
    ]),
    "Financing Preapproval": ("lender", "conditional-letter", [
        ("Dear Taylor Morgan", "Re: HCL-{id}, proposed acquisition of {address}. Lender preapproval is retained for the buyer and identified property. Harbor Community Lending preliminarily accepts an application for a conventional 30-year fixed loan amount of {loan}, subject to the conditions below. The proposed owner occupancy and purchase consideration were supplied with the application; a change in the accepted contract must be reported."),
        ("Conditions accompanying decision", "Provide the most recent complete asset statement, a current employment verification, the accepted agreement sequence, and insurance evidence effective at funding. Appraisal and title review are subject to the lender's final comparison with the accepted contract. Ordinary underwriting, appraisal, insurance, and final-document conditions remain before a clear-to-close may be issued. This preapproval is not a funding commitment and does not resolve an inconsistent price or an omitted party signature."),
        ("Processor's correspondence", "Documents uploaded August 25 are indexed to the application; indexing is not condition clearance. The processor will identify the response to each condition in the conditions list. Please avoid submitting only a selected statement page or a cropped image omitting the owner and period. Current contact: Morgan Lee, Harbor Community Lending. Requested closing coordination date: {closing}. No bank debit or loan proceeds have been released by this letter."),
    ]),
    "Loan Estimate": ("lender", "financial-table", [
        ("Application and terms", "Applicant: {buyer}. Loan HCL-{id}; property {address}; estimate issued August 20, 2026. Loan amount {loan}; purchase price reference {price}; product 30-year fixed, conventional; note rate 6.250%. Lock: not locked in this estimate. Monthly principal and interest {payment}. Prepayment penalty: none assumed. Balloon payment: none. Rate, fees, and timing remain subject to the lender's subsequent written offer."),
        ("Cost worksheet — buyer-paid estimates", "A | Origination processing | $1,250.00\nB | Appraisal service | $650.00\nB | Credit report | $85.00\nC | Title and settlement services | $2,350.00\nE | Recording charges | $250.00\nF | First-year hazard premium | $1,680.00\nF | Prepaid interest allowance | $1,000.00\nG | Initial tax/insurance reserves | $2,400.00\nJ | Estimated costs total | $9,665.00"),
        ("Cash and projected payments", "Down payment {down}; anticipated deposit credit {deposit}; loan proceeds {loan}. Estimated cash to close {cash} equals down payment plus $9,665.00 costs less anticipated deposit. An anticipated credit is not escrow confirmation. Monthly taxes and insurance allowance $790.00, consisting of $650.00 taxes and $140.00 insurance; no mortgage insurance is assumed at the stated 80 percent loan-to-value. Total illustrative monthly payment {monthly}. Taxes are estimates, not an assessor determination."),
    ]),
    "Closing Disclosure Draft": ("lender", "closing-table", [
        ("Draft issue and identification", "DRAFT — comparison copy, not a lender-issued final Closing Disclosure. Loan HCL-{id}; borrower {buyer}; seller {seller}; subject {address}. Proposed closing {closing}. Reference principal {loan}; term 360 months; fixed rate 6.250%; principal and interest {payment}. No prepayment penalty or balloon payment is assumed in this illustration. Delivery of this draft is not evidence that any required final disclosure waiting period has started or expired."),
        ("Borrower columns — at closing / before closing", "Origination | $1,250.00 | $0.00\nAppraisal | $0.00 | $650.00\nCredit report | $85.00 | $0.00\nTitle and settlement | $2,350.00 | $0.00\nRecording | $250.00 | $0.00\nHazard premium | $1,680.00 | $0.00\nPrepaid interest allowance | $1,000.00 | $0.00\nInitial reserves | $2,400.00 | $0.00\nTotal | $9,015.00 | $650.00"),
        ("Comparison and transaction accounting", "Total costs remain $9,665.00, matching the estimate's category total. Appraisal payment of $650.00 is now illustrated as paid before closing, reducing the remaining cash requirement by that amount without reducing total costs. Purchase consideration {price}; principal credit {loan}; anticipated deposit {deposit}; remaining illustrative cash {final_cash}. The deposit is a projected credit until confirmed by escrow. Seller compensation and payoff charges are not included in this borrower-only illustration."),
    ]),
    "Lender Conditions List": ("lender", "condition-register", [
        ("Application routing", "HCL-{id}; borrower {buyer}; subject {address}; processor Morgan Lee. This list accompanies the separately dated approval or preapproval letter. A document receipt date indicates receipt by the processor only. A condition is cleared only when the authorized review entry so states. The closing desk shall retain a prior condition if it is replaced by a more specific request."),
        ("Condition register", "01 | Income and employment | {condition}\n02 | Source of cash and full statements | {condition}\n03 | Appraisal accepted for subject | {condition}\n04 | Accepted agreement and amendments | {condition}\n05 | Hazard evidence and mortgagee | {condition}\n06 | Title instructions | {condition}\n07 | Final signing and funding | Future closing event; not recorded as completed"),
        ("Response instructions", "For condition 02, identify both sides of a transfer and retain the full statement period. For condition 04, submit the complete returned counterpart rather than a signature page without terms. For condition 05, use the property address and policy effective date, not a premium quote alone. A reference to an enclosure without the enclosure is not a complete response. Changes in loan amount or contract consideration require the processor to reconcile the application before requesting closing documents."),
    ]),
    "Appraisal Notice": ("lender", "valuation-letter", [
        ("Notice to applicant", "Harbor Community Lending application HCL-{id}; {buyer}; {address}. The appraisal review desk reports an opinion of value of {price}, effective August 26, 2026, for the subject fee-simple interest described in the appraiser's report. The notice is not the appraisal itself and contains neither a comparable-sales grid nor the appraiser's signed certification. A complete report copy should be requested through the lender's delivery channel."),
        ("Review entry and scope", "The notice reflects an appraised value at or above the {price} purchase price reference submitted with the application. No repair-based value condition is entered in this notice. This does not constitute a structural inspection, a property survey, an insurance replacement-cost estimate, or acceptance of a different contract price. The lender retains its final underwriting and funding conditions notwithstanding the value entry."),
        ("Applicant inquiry procedure", "A request to consider a factual correction should identify the report page, alleged error, and supporting evidence. A disagreement with value alone is not a corrected property fact. Do not contact a comparable property's occupants for confidential information on the lender's behalf. Any reconsideration response shall be retained with its date and shall not overwrite the original value notice. No additional appraisal fee is charged on this notice."),
    ]),
    "Seller Property Disclosure": ("disclosure", "checkbox-form", [
        ("Section A — equipment responses", "Subject {address}; seller {seller}; construction year reported 1988. The following seller responses describe installed items, not inspection certifications. Range/oven: present. Dishwasher: present. Water heater: present, garage location. Forced-air heat: present. Central cooling: present. Smoke and carbon-monoxide devices: reported present; buyer to verify operation. Pool/spa: no. Private well: no. Septic system: no. Leased solar equipment: no."),
        ("Section B — condition responses", "Roof leak known? No current leak reported. Past water entry? Yes — rear bedroom window, see continuation R-04. Foundation movement known? Not known. Plumbing repair during occupancy? Yes — kitchen faucet, R-09. Unpermitted room addition known? No. Boundary dispute known? No. Shared access agreement known? Not known beyond recorded matters. Insurance claim arising from R-04? No claim reported. Answers are seller statements rather than independent negative findings."),
        ("Section C — delivery", "Seller property disclosure is delivered for the identified property on August 24, 2026. Buyer acknowledgment is present. Seller supplied the continuation with service dates and identified the two invoices without warranting hidden conditions. The buyer receipt applies to this completed response set, not to an unseen inspection report. No disclosure response changes the contract price or requests a repair credit."),
    ]),
    "Seller Property Questionnaire": ("disclosure", "questionnaire", [
        ("Responses 1–6 — ownership and work", "Property {address}; respondent {seller}; residence occupied since 2017. 1. Lawsuits concerning property? No known pending proceeding. 2. Improvements during ownership? Faucet work and window resealing described in the continuation. 3. Permit copies for original construction? Not held by seller. 4. Alteration to bedroom count? No. 5. Encroachment allegation received? No. 6. Tree-root damage observed? Not observed; underground lines were not excavated."),
        ("Responses 7–12 — use and surroundings", "7. Regular neighborhood activity? Municipal refuse collection is audible on Tuesday mornings; occasional weekend landscaping noise. 8. Shared fence maintenance arrangement? Informal discussion only; no new written cost-sharing contract. 9. Drainage during heavy rain? Temporary ponding near rear planter, dispersing after rain. 10. Short-term rental use? None by seller. 11. Animals kept? One indoor cat. 12. Pest service? Routine exterior service; see separate wood-organism report for its own observations."),
        ("Response 13 — supplied papers", "Service receipt R-04 dated April 16, 2021 concerns resealing, not replacement of the entire window or remediation behind walls. R-09 dated June 9, 2023 concerns faucet and connectors only. Seller has not represented these papers as a permit history or comprehensive maintenance log. No compensation is requested for the included manuals. Questionnaire delivered August 24 with the property disclosure; buyer's receipt below covers both continuations."),
    ]),
    "Natural Hazard Disclosure": ("disclosure", "hazard-schedule", [
        ("Order cover", "Harborfield Mapping Services, fictional order NHD-{id}-0824. Subject {address}; APN {apn}. Requested by Rowan Price for the resale packet. This is a fictional hazard-provider report, not an official map determination. Report date August 24, 2026. The following entries are supplied scenario assumptions and must not be used to determine any real property's hazard classification."),
        ("Schedule H — location screening", "Special flood hazard area | Not indicated in fictional screening\nDam inundation area | Not indicated\nVery high fire hazard area | Not indicated\nWildland responsibility area | Not indicated\nEarthquake fault zone | Not indicated\nSeismic hazard zone | Not indicated\nMap reference | DEMO-HF-2026, invented index; no actual agency panel asserted"),
        ("Provider explanatory notice", "A parcel outside a mapped area can experience flood, fire, shaking, slope failure, or another loss. A parcel near a boundary may require a more specific determination than the parcel-centroid screening used for this fictional schedule. The schedule does not quote an insurance premium, evaluate defensible space, or establish building-permit eligibility. Natural hazard disclosure is delivered and acknowledged on August 24. Location questions should identify the APN as well as the street description so that a map correction is not applied to the wrong parcel."),
    ]),
    "Agent Visual Inspection Disclosure": ("inspection", "room-report", [
        ("Visit particulars", "Subject {address}. Avery Chen accompanied Rowan Price for an accessible-area visual walk on August 24, 2026, 10:15–10:55. Clear weather; electricity and water on; seller belongings present. This is the agents' observation record, not a licensed specialist's test report. The agent observations below refer only to readily observable conditions at the visit."),
        ("Room-by-room entries", "Entry/hall: small scuff at lower east wall; no open floor covering seam observed. Living room: patch in painted ceiling near former light position, origin not established. Kitchen: faucet operated; cabinet base dry at visit. Rear bedroom: discoloration at lower window trim, seller refers to resealing receipt R-04. Hall bath: worn sealant at tub edge. Garage: boxes restricted view of west wall. Exterior: rear planter showed soil settlement adjacent to edging."),
        ("Communication entry", "Observations transmitted to buyer August 24 with seller disclosure and the separate inspection reference. No request to open the rear bedroom wall was made during this visit. The agent has not determined whether the discoloration represents current moisture. Buyer may consult the home inspector about the location and the limits of the seller's repair receipt. No agent statement here certifies the roof, electrical system, sewer lateral, or structural adequacy."),
    ]),
    "Inspection Report Summary": ("inspection", "inspection-report", [
        ("Assignment HI-{id}", "Harborfield Home Review, fictional residential inspection service. Subject {address}; client {buyer}; inspection August 25, 2026, 09:00–12:10. Inspector: Ellis Navarro, fictional credential DEMO-HI-21. This expanded inspection record addresses visible residential components; it is not a government certification. No unresolved repair negotiation is entered in this report."),
        ("Observed components", "R-01 Roof: viewed from accessible eaves and grade; scattered surface wear, no active leak observed in accessible interior. E-02 Kitchen receptacle: tested at accessible counter location; reset operated. P-03 Hall bath: minor faucet aerator mineral buildup; cleaning advised. H-04 Heating: thermostat call produced warm air at sampled registers; heat exchanger not dismantled. W-05 Rear window: old trim staining, dry to limited surface observation; correlate seller receipt. G-06 Garage: west wall partially concealed by storage."),
        ("Maintenance and referral", "Routine sealant renewal at tub and inspection of planter drainage before winter are recommended maintenance, not negotiated seller obligations. Obtain specialized evaluation if water entry recurs at W-05. The inspection did not sample indoor air, test lead, scope the sewer, or establish concealed foundation condition. Buyer acknowledgment is retained; no agreement to waive a separate title or loan condition is included in this report."),
    ]),
    "Inspection Contingency Removal": ("contract", "election", [
        ("Election addressed to seller", "Buyer {buyer}, property {address}, agreement dated August 18, 2026. The inspection contingency only is removed by this signed notice delivered August 28, 2026 at 15:20. The recorded inspection deadline is August 29, 2026. Buyer inspection contingency removal is signed before the recorded deadline. No other box or election is incorporated by reference merely because the word 'contingency' appears in another record."),
        ("Items not removed by this notice", "Financing, appraisal, title, and disclosure review are not removed by this inspection-only election. No release of a title exception, acknowledgment of lender funding, or acceptance of a changed purchase price is made. Buyer considered the delivered inspection observations and has not conditioned this notice on an unaccepted repair request. A later agreement concerning a repair must identify its own obligations and consideration."),
        ("Delivery receipt", "Avery Chen transmitted the notice to Rowan Price and copied escrow file {escrow}. The recipient's receipt is an administrative acknowledgment, not a seller amendment. Retain the whole notice with the inspection correspondence; a copied signature detached from the limitation above is not an equivalent instrument. Seller's signature is not required for this buyer election and no blank seller execution line is supplied."),
    ]),
    "Final Walk-Through Record": ("inspection", "appointment-checklist", [
        ("Appointment notice — not a completed inspection", "Buyer {buyer}; property {address}; proposed visit September 14, 2026 at 16:00 with Avery Chen. Status: SCHEDULED. Final walk-through is scheduled close to the anticipated closing date {closing}. No attended-visit result, condition acceptance, or final buyer signature is recorded as of the August 28 packet date."),
        ("On-site worksheet to be completed at visit", "Included appliances | Not yet observed at final visit\nDebris and personal-property removal | Not yet observed\nNew damage since inspection | Not yet observed\nKeys and remotes | Delivery to follow possession instruction\nAgreed repairs | No separately negotiated repair obligation in current packet\nUtilities operating | To be checked at appointment"),
        ("Coordinator's instruction", "Compare observed condition with the inspection record and written included-property terms. Do not mark an item complete because the seller expects to complete it later. Photograph a material change and identify its room or location before requesting a response. If access is unavailable, enter the reason and arrange a new appointment rather than acknowledging an unperformed walk-through. Receipt of this appointment notice does not confirm that possession or keys have been delivered."),
    ]),
    "Pest and Wood-Destroying Organism Report": ("inspection", "pest-report", [
        ("Order and scope", "Fictional operator Harborfield Timber Review; work order WDO-{id}; {address}; ordered by {buyer}. Visit August 25, 2026. Inspection type: accessible-area visual; no destructive opening. Diagram key: A front entry, B garage, C rear planter, D attic hatch. Inspector Casey Bell, invented registration DEMO-WDO-08. No actual state-issued clearance is represented."),
        ("Numbered findings", "1A | Entry trim | No visible active wood-destroying infestation in accessible trim.\n1B | Garage sill | Accessible portion visually examined; west storage area excluded.\n2A | Rear planter | Maintain separation of soil and wood edging; preventive maintenance.\n3A | Concealed wall interiors | Not accessed; no finding about concealed organisms.\n4A | Treatment recommendation | No open treatment or clearance requirement recorded for examined areas."),
        ("Completion and exclusions", "No pesticide application, drilling, fumigation, structural repair, or clearance reinspection was performed under this order. A maintenance suggestion is not a treatment certificate. If stored items are moved, an additional inspection can address the newly accessible area. Any later bid shall list the numbered finding it covers and identify whether concealed damage discovered during work changes its scope. Owner receipt does not adopt an opinion about excluded wall interiors."),
    ]),
    "Possession and Repair Confirmation": ("contract", "possession-schedule", [
        ("Possession schedule P", "Property {address}; parties {buyer} and {seller}. Possession is planned upon the contractually required closing/recording confirmation and delivery arrangement, not the execution of this coordination record. No post-closing tenancy or separate rent-back is agreed. No rental rate, security deposit, or occupancy extension is established. Seller shall remove excluded personal property and refuse before the agreed transfer."),
        ("Repair reconciliation", "Inspection references R-01 through G-06 remain observations. No separately negotiated repair credit or seller repair contract is entered. The prior window resealing and faucet service are historical work, not new closing obligations. No additional settlement credit is to be inferred from a maintenance suggestion. If the parties later agree to work, the instrument shall state the responsible person, completion date, invoice requirement, and treatment of incomplete work."),
        ("Access devices and final confirmation", "Included access items: two garage remotes and available exterior-door keys. Device counts are to be verified at delivery; the present record does not certify receipt. Buyer may arrange rekeying after authorized possession. The final walk-through is separately scheduled for September 14, 2026. Any material change reported there shall be presented to the parties before an inconsistent completion entry is made."),
    ]),
    "Preliminary Title Report": ("settlement", "title-schedules", [
        ("Schedule A — description of interest", "Fictional Harborfield Title Services file PT-{id}, effective August 24, 2026 at 07:30. Property {address}; APN {apn}. Interest: fee simple. Seller vesting shown: {seller}, an individual. Proposed insured purchaser: {buyer}, final manner of vesting subject to written instruction. Legal description: {legal}. This preliminary report identifies proposed title conditions; it is not the issued policy."),
        ("Schedule B — exceptions", "1. Current fiscal-year real property taxes, payable as provided by the taxing authority; final proration to settlement. 2. Recorded utility easement along the rear five feet of the described lot; no new encroachment determination is supplied. 3. Matters disclosed by an accurate survey or physical inspection, to the extent provided in the contemplated policy. 4. Rights of persons in possession, if any, other than the disclosed seller occupancy. The listed standard exceptions are not a statement that a newly discovered defect has been cured."),
        ("Schedule B — supplemental entry 5", "{title_status} Title officer Jordan Reyes shall retain the instrument reference and the evidence supporting any deletion from the proposed exceptions. A request for evidence is not equivalent to receiving it. Do not remove a recorded item solely because another party believes it will be paid from sale proceeds."),
        ("Schedule C — proposed issuance", "Obtain the final signed conveyance and accepted vesting instruction matching the legal description. Update the search through the applicable issuance period and reconcile intervening instruments before the final policy is issued. No survey, mineral-interest opinion, zoning guarantee, or tax exemption is included. The premium and policy amount shall be confirmed with the title desk rather than inferred from an unaccepted negotiation."),
    ]),
    "Estimated Closing Statement": ("settlement", "settlement-ledger", [
        ("Buyer estimated ledger", "Harborfield Title & Escrow file {escrow}; subject {address}; buyer {buyer}; seller {seller}; intended close {closing}. Buyer-only planning statement, not a combined final settlement. Preparation date August 28, 2026. The contract consideration entered below remains subject to resolution of any conflicting accepted instrument."),
        ("Debit / credit schedule", "Purchase consideration | Debit {price}\nClosing costs including reserves | Debit $9,665.00\nExpected lender principal | Credit {loan}\nAnticipated earnest-money deposit | Credit {deposit}\nIllustrative remaining cash | {cash}\nSeller proceeds | Not calculated in buyer-only ledger\nPayoff disbursement | No authorization entered"),
        ("Adjustments and explanatory entries", "The $9,665.00 cost allowance consists of $1,250 origination, $650 appraisal, $85 credit report, $2,350 title/settlement, $250 recording, $1,680 hazard premium, $1,000 prepaid-interest allowance, and $2,400 initial reserves. A charge paid separately before closing must be credited once in the final remaining-cash calculation. Deposit credit is projected and must be matched to the receipt status; a delivery reference alone is not a bank receipt. No association transfer fee or seller repair allowance is entered."),
    ]),
    "Seller Withholding and Vesting Review": ("settlement", "vesting-worksheet", [
        ("Identity and proposed deed entries", "File {escrow}; {address}; APN {apn}. Current named seller {seller}; proposed purchaser {buyer}. Preliminary title describes the seller as an individual. Buyer has not elected a trust, partnership, or corporation in this worksheet. Exact final vesting language is to be supplied by the parties with appropriate advice; the preparer is not choosing a legal ownership form for them."),
        ("Tax document routing", "Seller identification received for file matching; taxpayer number intentionally absent from this counterpart. California withholding treatment: refer to seller's completed current certification and escrow/tax review; no exemption determined here. Federal foreign-person certification: request through the settlement channel; no conclusion based on mailing address or citizenship assumption. No withholding amount, tax rate, or zero-tax representation is entered in this coordination worksheet."),
        ("Authority and privacy", "A person signing under a power of attorney or for an entity must supply authority acceptable to title and escrow; no such alternate signatory is proposed in the current identity entry. A misspelled name shall be corrected consistently before the deed is prepared. Tax forms containing full identifiers shall remain in the restricted settlement file, not appended to the general buyer packet. The title officer's preparation acknowledgment below is not a seller tax certification."),
    ]),
    "Homeowners Insurance Binder": ("insurance", "binder", [
        ("Fictional evidence of bound coverage", "Issuer Harborfield Mutual Demo Company; agency Harbor Coast Coverage; binder DEMO-HO-{id}. Named insured {buyer}; premises {address}; owner-occupied single-family residence, construction year 1988. Effective {closing} at 12:01 a.m.; binder expires 30 days later unless replaced by policy evidence. This fictional binder records bound coverage for the scenario, not a quotation; it creates no real insurance."),
        ("Coverage schedule", "A | Dwelling replacement-cost limit | $650,000\nB | Other structures | $65,000\nC | Personal property | $325,000\nD | Loss of use | $130,000\nE | Personal liability | $300,000\nAll-peril deductible | $2,500\nAnnual premium | $1,680\nMortgagee | Harbor Community Lending, its successors/assigns as interests appear"),
        ("Binder entries", "Agent Riley Brooks entered the scenario binder August 27, 2026 at 14:45. Coverage amount reflects the stated replacement-cost estimate and is not the purchase price or appraised land value. Separate flood and earthquake coverage are not included in this schedule. Final lender funding remains subject to its own verification of required insurance evidence. Changes to the effective date must be endorsed by the issuing agent rather than handwritten by escrow."),
    ]),
    "Insurance and Flood Evaluation": ("insurance", "coverage-comparison", [
        ("Coverage review memorandum", "Borrower {buyer}; property {address}; loan HCL-{id}. Review date August 28, 2026; preparer Riley Brooks. Compared the fictional binder DEMO-HO-{id} with the lender's requested dwelling evidence. Dwelling limit $650,000, deductible $2,500, annual premium $1,680. The lender loss-payee/mortgagee entry identifies Harbor Community Lending; coverage is separate from the purchase price."),
        ("Flood and optional-peril comparison", "The fictional location screen in NHD-{id}-0824 indicates no special flood hazard area. No actual FEMA panel, elevation certificate, or lender standard determination is reproduced. No documented special flood-insurance condition appears in the supplied lender record. Standard homeowners coverage excludes flood in this illustration. Optional flood and earthquake quotations: not requested in the retained correspondence; absence of a lender condition is not an assurance against those losses."),
        ("Borrower discussion record", "Discussed the difference between a lender minimum and the owner's chosen protection. A higher deductible reduces some premiums but changes the owner's retained loss. Personal-property limits and exclusions should be reviewed against the buyer's possessions and use. No representation was made that future renewal is guaranteed or that every weather-related loss is covered. The borrower acknowledgment below records receipt of this comparison, not a waiver of the ability to request additional coverage."),
    ]),
    "Wire Fraud Advisory": ("settlement", "verification-log", [
        ("Payment instruction acknowledgment", "To {buyer}, file {escrow}, property {address}. Never act on changed payment instructions solely because they appear in an existing email thread. Before a transfer, independently contact the established escrow office through a previously verified number. Do not use a replacement telephone number supplied in the same message as the proposed bank change. No account, routing number, QR payment code, or clickable payment destination is supplied in this advisory."),
        ("Verification log", "August 20, 2026 10:05 | Avery Chen explained call-back procedure to buyer.\nAugust 20, 2026 10:12 | Buyer acknowledged retaining independently verified office contact.\nPayment-detail confirmation | To be performed with escrow for each actual transfer.\nAuthority granted to software | None.\nChanged instruction received | None recorded on this advisory date."),
        ("If a suspicious request is received", "Stop the proposed transfer and contact the escrow office through the established channel. Preserve the message and its attachments without replying with confidential account information. If money has already been sent, contact the financial institution immediately through its verified fraud channel and notify the transaction professionals. This advisory does not state that a transfer has occurred and does not substitute for the actual verification call. Buyer acknowledgement confirms receipt of the procedure, not authorization for an agent to transmit funds."),
    ]),
    "Lead-Based Paint Applicability Notice": ("disclosure", "applicability-election", [
        ("Construction-year entry", "Property {address}; APN {apn}; construction year recorded as 1988 in the supplied property profile. Election for this fictional packet: pre-1978 lead-based-paint disclosure path not applicable on the stated construction year. The entry is an applicability screen, not a laboratory finding that paint or soil contains no lead. Seller has not supplied a lead inspection, risk assessment, or abatement certificate."),
        ("Supporting response and limitations", "Seller reports no knowledge of an earlier dwelling incorporated into this structure and has not supplied original permit drawings. If an assessor correction or other credible record indicates pre-1978 housing, the applicability entry must be revisited and the appropriate disclosure process obtained. Do not create a buyer waiver of an inspection opportunity from this not-applicable election. No test result is inserted in the seller-knowledge field."),
        ("Delivery notation", "Prepared August 24, 2026 and delivered with the construction-year source reference. Buyer receipt records delivery of the applicability entry only. Renovation safety and occupational exposure are separate questions from the resale disclosure screen; a proposed contractor should evaluate its own work requirements. No promise about the composition of replacement windows, imported fixtures, or later paint is made by the construction-year entry."),
    ]),
    "Fire Hazard Severity Zone Notice": ("disclosure", "fire-screen", [
        ("Location entry F-1", "Subject {address}; APN {apn}; construction year 1988. Fictional screen DEMO-HF-FIRE-0824 reports no triggered additional fire-zone notice for this scenario. No real state or local map panel or inspection certificate is claimed. This entry is paired with NHD-{id}-0824 rather than represented as an official agency determination."),
        ("Property observations F-2", "Visible rear planter abuts landscape edging; detached storage and tree canopies were not measured for defensible-space compliance. Seller has not supplied a current fire-district clearance or a home-hardening retrofit certificate. Roof-covering age is not established by this screen. No inspection pass, violation, or compliance deadline is fabricated. A local agency determination, if obtained, must identify the parcel, inspection date, and corrections required."),
        ("Buyer notice F-3", "Fire exposure can exist outside a mapped severity zone. Insurability and premium are determined separately by the insurer. If a later location review changes the applicability result, obtain the appropriate notices and any required local inspection through the responsible professionals. Receipt of this screen neither certifies defensible space nor excuses maintenance. The disclosure recipient should retain the later map or inspection version when a corrected result is issued."),
    ]),
    "Mello-Roos and 1915 Act Notice": ("disclosure", "tax-schedule", [
        ("Parcel assessment worksheet", "Subject {address}; parcel {apn}; review date August 24, 2026. This is a fictional resale tax/assessment worksheet, not a statutory subdivider notice. Ordinary ad valorem taxes remain subject to the actual assessor and collector records. No separate Mello-Roos community facilities district charge or 1915 Act assessment is identified in the supplied fictional index."),
        ("District response fields", "Community facilities district name | None identified in supplied index\nSpecial tax maximum/escalator | Not entered; no district identified\nImprovement bond assessment | None identified in supplied index\nBond balance and remaining term | Not established by this worksheet\nSupplemental assessment after transfer | Not calculated\nResponsible inquiry channel | Tax collector/assessor through independently verified contact"),
        ("Buyer acknowledgment of scope", "A blank district amount is not a guarantee of a zero future tax bill. Transfer may affect assessment and supplemental billing independently of any special district. If a title exception, seller notice, or tax bill identifies a district, obtain its current parcel-specific amount, escalation provisions, and applicable term before substituting a figure in closing estimates. This worksheet makes no tax exemption election and gives no assurance that an estimate will equal the next bill."),
    ]),
    "HOA and Common Interest Applicability": ("disclosure", "association-matrix", [
        ("Applicability statement", "Property {address}; seller {seller}. No HOA or common-interest development is reported in the supplied fictional single-family property record. No association manager, dues account, transfer application, or membership number is identified. A recorded utility easement is not by itself evidence of an association. This response should be compared with the title description before an association relationship is inferred."),
        ("Document matrix — conditional request", "CC&Rs and bylaws | Not requested: no association identified\nBudget and reserve information | Not applicable to reported ownership\nAssessment and delinquency statement | No association account identified\nMinutes and pending litigation | No governing association identified\nTransfer fee and move rules | No fee entered\nInsurance and structural reports | No association report represented as received"),
        ("Change in applicability", "If later evidence identifies a common-interest development, replace this screen with a request to the responsible association for the applicable governing, financial, assessment, insurance, and transaction documents. Do not treat the not-requested rows as satisfied evidence for an association that is later discovered. Buyer receipt concerns the present seller response, not an independent legal determination about recorded restrictions. Private covenants may require review even where no dues-paying association is identified."),
    ]),
    "Local and Property System Applicability": ("disclosure", "systems-matrix", [
        ("Utility and equipment entries", "Subject {address}; parcel {apn}. Public water and public sewer reported; electric and gas service connected. No private well, septic disposal, leased solar array, propane tank lease, or recorded equipment-financing agreement is disclosed. These entries identify the reported service arrangement, not testing of water quality, sewer condition, electrical capacity, or gas-line integrity."),
        ("Local inquiry matrix", "Sewer lateral transfer certificate | No actual local certificate reproduced\nWater-conservation retrofit | Fixtures present; no official compliance certification\nAirport/noise notice | No special notice identified in supplied packet\nPrivate-road maintenance | No private-road agreement reported\nZoning and permitted use | Residential use reported; no zoning opinion issued\nSolar transfer | No leased equipment reported\nWell/septic transfer | Not applicable to reported public connections"),
        ("Property-specific follow-up", "The fictional city name is not a source of actual municipal requirements. For a real transaction, confirm the jurisdiction and its transfer ordinances before marking a local requirement applicable or complete. A sewer service connection does not establish that a private lateral has passed a pressure or camera test. An inspection invoice must identify the tested portion and date. A later equipment lease or financing notice should be reviewed for consent and payoff requirements rather than being treated as an included fixture without obligations."),
    ]),
}


def populate_document(transaction: dict, document: dict) -> None:
    """Material facts come from authored records; signatures reflect source state."""
    name = document["name"]
    family, layout, sections = PROFILES[name]
    seed = document["text"].split("\n\n", 1)[0]
    docs = transaction["documents"]
    approval = any(d["name"] == "Financing Approval" for d in docs)
    missing = "Seller signature missing" in next(d["text"] for d in docs if d["name"] == "Purchase Agreement")
    pending = "pending confirmation" in next(d["text"] for d in docs if d["name"] == "Deposit Receipt")
    title_blocked = "requires written payoff" in next(d["text"] for d in docs if d["name"] == "Preliminary Title Report")
    price, deposit = transaction["purchasePrice"], transaction["depositAmount"]
    loan = round(price * .8)
    rate = .0625 / 12
    payment = loan * rate / (1 - (1 + rate) ** -360)
    money = lambda value: f"${value:,.2f}"
    values = dict(id=transaction["id"], buyer=transaction["parties"]["buyer"], seller=transaction["parties"]["seller"],
                  address=transaction["property"], apn=transaction["propertyDetails"]["APN"], legal=transaction["propertyDetails"]["legalDescription"],
                  escrow=transaction["escrowDetails"]["escrowNumber"], closing=transaction["closingDate"], price=money(price), deposit=money(deposit),
                  loan=money(loan), down=money(price-loan), cash=money(price-loan+9665-deposit), final_cash=money(price-loan+9015-deposit),
                  payment=money(payment), monthly=money(payment+790), commission=money(price*.025),
                  condition="Cleared by underwriting August 28, 2026" if approval else "Submitted for ordinary underwriting review; not marked clear-to-close",
                  receipt_status=("Earnest money receipt remains pending confirmation from escrow. Received amount: NOT CONFIRMED. Posting timestamp: NOT RETURNED. Escrow confirmation number: NOT RETURNED. The buyer's delivery request is retained without representing that funds are unavailable." if pending else f"Earnest money receipt confirmed by escrow. Received amount: {money(deposit)}. Posting timestamp: August 21, 2026 at 10:42. Funds reference: DEMO-POST-{transaction['id']}-01. Clerk: Casey Morgan; amount matched to deposit requirement."),
                  title_status=("Instrument DEMO-LIEN-2021-0048, recorded July 14, 2021, in favor of Harborfield Private Credit: stated original obligation $18,400. This recorded lien exception requires written payoff or release evidence before closing. Payoff approval: not supplied. Release recording: not supplied. Escrow confirmation of clearance: not supplied." if title_blocked else "No unresolved lien exception requiring transaction escalation is identified. No supplemental monetary lien is entered under item 5 in this fictional search. Standard exceptions above remain subject to normal title and escrow review."))
    blocks = [{"heading": heading, "body": body.format(**values)} for heading, body in sections]
    # Place operative terms among record-specific entries, not in a universal answer box.
    for index, (heading, body) in enumerate(FAMILY_TERMS[family]):
        blocks.insert(min(2 + index * 2, len(blocks)), {"heading": heading, "body": body})
    signatures: list[str] = []
    if name == "Purchase Agreement":
        signatures = ["Buyer: /s/ Taylor Morgan — simulated electronic signature, August 18, 2026 16:02.",
                      "Seller signature missing. No seller execution timestamp returned." if missing else "Seller: /s/ Jamie Ellis — simulated electronic signature, August 18, 2026 17:14. Execution log: buyer and seller signatures present."]
    elif name == "Counteroffer":
        signatures = ["Proposing seller: /s/ Jamie Ellis — simulated signature, August 19, 2026 14:05.", "Buyer acceptance: NOT RETURNED. No buyer acceptance signature or timestamp exists in this counterpart."]
    elif name == "Final Walk-Through Record":
        signatures = ["Appointment coordinator: /s/ Avery Chen — simulated acknowledgment, August 28, 2026 09:15.", "Buyer completed-visit acknowledgment: NOT YET DUE — visit has not occurred."]
    elif name == "Deposit Receipt":
        signatures = ["Prepared: /s/ Casey Morgan — simulated cash-desk entry, August 28, 2026 09:30.", "Acknowledgment is of preparation only; funds remain unconfirmed." if pending else "Receipt attestation: /s/ Casey Morgan — simulated confirmation of the posting entry above."]
    elif name in {"Amendment #1", "Possession and Repair Confirmation"}:
        signatures = ["Buyer: /s/ Taylor Morgan — simulated signature, August 27, 2026 14:20.", "Seller: /s/ Jamie Ellis — simulated signature, August 27, 2026 15:05. This signature applies only to this instrument."]
    elif name in {"Agency Disclosure", "Commission Agreement", "Inspection Contingency Removal", "Wire Fraud Advisory"}:
        signatures = ["Buyer: /s/ Taylor Morgan — simulated acknowledgment, August 20, 2026 10:20." if name != "Inspection Contingency Removal" else "Buyer: /s/ Taylor Morgan — simulated election, August 28, 2026 15:15.", "Representative: /s/ Avery Chen — simulated delivery acknowledgment; not a signature for the seller."]
    elif family == "disclosure":
        signatures = ["Respondent/preparer: /s/ Jamie Ellis — simulated acknowledgment, August 24, 2026 13:10.", "Buyer receipt: /s/ Taylor Morgan — simulated receipt, August 24, 2026 18:25; receipt is not a waiver."]
    else:
        signer = {"lender": "Morgan Lee", "inspection": "Ellis Navarro", "settlement": "Casey Morgan", "insurance": "Riley Brooks"}[family]
        if name == "Agent Visual Inspection Disclosure": signer = "Avery Chen and Rowan Price"
        if name == "Pest and Wood-Destroying Organism Report": signer = "Casey Bell"
        if name == "Preliminary Title Report": signer = "Jordan Reyes"
        signatures = [f"Prepared/issued: /s/ {signer} — simulated electronic record, August 28, 2026 10:00.", "Electronic copy certified complete by the fictional preparer; not a public-official certification or authorization to close."]
    execution_heading = {
        "contract": "Signatures and electronic audit trail",
        "lender": "Authorized lending correspondence",
        "disclosure": "Seller response and buyer receipt",
        "inspection": "Inspector / recipient acknowledgments",
        "settlement": "Settlement preparer certification",
        "insurance": "Issuing representative and insured receipt",
    }[family]
    blocks.append({"heading": execution_heading, "body": "\n".join(signatures)})
    text = "\n\n".join(f"{b['heading'].upper()}\n{b['body']}" for b in blocks)
    document.update(text=text, blocks=blocks, layout=layout, family=family, page=1,
                    sourceHash=sha256(text.encode()).hexdigest(), sourceFormat="Complete, paginated fictional transaction record (PNG/PDF)")
