"""Synthetic, source-locked California resale packets for the Doorlight demo only."""
from __future__ import annotations
from copy import deepcopy
import re
from .document_content import populate_document
from .document_pages import page_texts

BASE_CHECKLIST = ["Executed agreement", "Agency disclosure", "Deposit confirmation", "Financing evidence", "Seller and hazard disclosures", "Clear title path", "Contingency disposition", "Closing authorization"]
EXTRACTION_TARGETS = {
 "Purchase Agreement":["buyer and seller names","property address and APN","purchase price","deposit","financing and contingency dates","signatures"],
 "Amendment #1":["amended term","effective date","signatures","whether it supersedes a prior term"], "Counteroffer":["revised purchase price","party acceptance","superseding-document language"],
 "Deposit Receipt":["deposit amount","escrow receipt status","funds reference","receipt date"], "Agency Disclosure":["representation relationship","buyer acknowledgment","broker acknowledgment"],
 "Financing Approval":["lender status","loan amount","clear-to-close conditions","buyer and property match"], "Financing Preapproval":["lender status","loan amount","buyer and property match","remaining lender conditions"],
 "Loan Estimate":["loan program","interest rate","cash to close","estimated payment","rate-lock status"], "Closing Disclosure Draft":["closing date","cash to close","loan terms","closing costs","settlement agent"],
 "Seller Property Disclosure":["delivery status","buyer acknowledgment","property condition statements"], "Natural Hazard Disclosure":["delivery status","hazard zones","buyer acknowledgment"],
 "Preliminary Title Report":["vesting","legal-description match","lien or title exceptions","required release evidence"], "Escrow Instructions":["escrow holder","escrow number","wire fraud controls","proration instructions"],
 "Inspection Report Summary":["inspection date","material observations","repair requests","buyer acknowledgment"], "Inspection Contingency Removal":["contingency type","signature","date","deadline relationship"],
 "Appraisal Notice":["appraised value","value condition","lender review status"], "Homeowners Insurance Binder":["carrier","effective date","coverage amount","lender loss-payee status"],
 "Wire Fraud Advisory":["buyer acknowledgment","verification procedure","external-payment warning"], "Final Walk-Through Record":["walk-through date","property condition","outstanding items","buyer acknowledgment"],
 "Agent Visual Inspection Disclosure":["agent observations","material facts readily observable","buyer delivery acknowledgment"],
 "Seller Property Questionnaire":["seller knowledge responses","repairs","water intrusion","systems and neighborhood conditions"],
 "Lead-Based Paint Applicability Notice":["property construction year","pre-1978 applicability","disclosure or not-applicable result"],
 "Fire Hazard Severity Zone Notice":["fire-zone applicability","construction-year condition","buyer notice"],
 "Mello-Roos and 1915 Act Notice":["special tax applicability","assessment district result","buyer notice"],
 "HOA and Common Interest Applicability":["HOA applicability","governing documents","dues and transfer fees"],
 "Local and Property System Applicability":["local disclosure applicability","well septic and sewer status","solar and leased-equipment status"],
 "Pest and Wood-Destroying Organism Report":["inspection scope","findings","clearance or treatment recommendation"],
 "Insurance and Flood Evaluation":["homeowners coverage","flood-zone review","deductible and lender requirements"],
 "Lender Conditions List":["underwriting conditions","income asset and credit verification","clear-to-close status"],
 "Estimated Closing Statement":["buyer debit credit categories","tax and utility prorations","cash-to-close comparison"],
 "Seller Withholding and Vesting Review":["seller tax withholding applicability","vesting names","deed-signing requirements"],
 "Possession and Repair Confirmation":["possession terms","agreed repair credit status","final walk-through follow-up"],
 "Commission Agreement":["approved commission percentage","broker and agent split","fees","calculation restrictions"],
}
def _document(name, version, page, text, controlling=False):
    """Declare source identity; complete body/layout is added after case assembly."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return {
        "name": name, "version": version, "page": page, "text": text,
        "classification": name, "sourceHash": "pending-content-hash",
        "receivedAt": "2026-08-28T16:00:00Z", "controlling": controlling,
        "sourceFormat": "Pending generated source", "visionEligible": True,
        "extractionTargets": EXTRACTION_TARGETS.get(name, ["document identity", "material facts", "dates", "exception language"]),
        "assetSlug": slug,
    }
def _case(case_id,address,price,closing,documents,**overrides):
    loan=round(price*.80)
    value={"id":case_id,"property":address,"propertyType":"Single-family residence","side":"Buyer","type":"Resale","financing":"Conventional","representation":"Represented buyer","jurisdiction":"California","brokerage":"Doorlight Demo Brokerage","source":"Accepted offer and retained synthetic transaction packet — demo data only","parties":{"buyer":"Taylor Morgan","seller":"Jamie Ellis","buyerAgent":"Avery Chen","listingAgent":"Rowan Price","escrowOfficer":"Casey Morgan","lender":"Harbor Community Lending","titleOfficer":"Jordan Reyes"},"purchasePrice":price,"depositAmount":round(price*.03),"closingDate":closing,
    "propertyDetails":{"APN":"084-221-019","legalDescription":"Lot 19, Harbor View Tract No. 18","yearBuilt":"1988","occupancy":"Buyer intends owner occupancy","HOA":"No HOA reported","utilities":"Public water, sewer, electric, and gas","parcelReview":"Address, APN, and legal description queued for title comparison"},
    "financingDetails":{"loanProgram":"30-year fixed conventional","loanAmount":f"${loan:,.0f}","loanToValue":"80% estimated","rateLock":"Review current lender record","appraisal":"See appraisal notice","insurance":"Binder required before funding","cashToClose":"Compare latest lender and escrow figures"},
    "escrowDetails":{"holder":"Harborfield Title & Escrow","escrowNumber":f"HF-2026-{case_id}","vesting":"Taylor Morgan, subject to final title review","prorations":"Taxes, utilities, and HOA if applicable","wireControls":"Verify instructions by known phone number; never rely on changed email instructions","recording":"Escrow/title confirmation required"},
    "importantDates":{"acceptedOffer":"August 18, 2026","depositDue":"August 21, 2026","inspectionDeadline":"August 29, 2026","appraisalDeadline":"September 3, 2026","loanContingency":"September 5, 2026","disclosureReview":"September 7, 2026","finalWalkThrough":"September 14, 2026","closing":closing,"recording":"Targeted after signed closing package and funding"},
    "policyContext":{"policyId":"CA-BUYER-RESALE-CONVENTIONAL","version":"1.0","checklist":BASE_CHECKLIST},"commission":{"agreementStatus":"Not evaluated in this seven-agent MVP","sidePercent":2.5,"brokerSplitPercent":20,"agentSplitPercent":80,"fees":495},"approvals":{"transactionCoordinator":"Demo review","broker":"Not required unless escalated","closingAuthorization":"Not a closing authorization","humanReview":"Required for legal ambiguity, material conflicts, and Amber/Red risk"},"communication":{"permittedRecipients":["Transaction Coordinator","Buyer Agent","Broker"],"allowedActions":["Create internal task","Draft reminder","Draft message"],"externalSendingEnabled":False},"closing":{"escrow":"Review retained instructions and confirmation","title":"See retained title report","financing":"See retained lender records","closingDisclosure":"Compare with Loan Estimate when issued","packageStatus":"Synthetic demo; no real close may be executed","recordFrozen":False},"documents":documents}
    value.update(overrides);return value
def _packet(price,closing,deposit,finance_name,finance,title,agreement,amendment,extra=None):
    docs=[
      _document("Purchase Agreement","v2",4,agreement,True),_document("Amendment #1","v1",2,amendment,True),
      _document("Escrow Instructions","v1",3,f"Escrow file HF-2026 is opened with Harborfield Title & Escrow. Purchase price is ${price:,.0f}; estimated closing is {closing}. Written instructions require escrow to hold funds, coordinate prorations, obtain lender funding confirmation, and confirm recording. Buyer received a wire-fraud advisory and must independently verify any payment instructions."),
      _document("Deposit Receipt","v2",1,deposit),_document("Agency Disclosure","v1",1,"Buyer representation disclosure identifies Doorlight Demo Brokerage and Avery Chen as the buyer-side representative. Buyer and brokerage acknowledgments are present. The record states that transaction organization is not legal, tax, lending, or appraisal advice."),
      _document("Commission Agreement","v1",2,"Approved buyer-side commission terms identify a 2.5 percent gross commission calculation from the purchase price, followed by an 80 percent agent and 20 percent broker split before the stated $495 fee. This record supports an advisory calculation only; it is not an invoice, payment authorization, disbursement instruction, or external accounting action."),
      _document(finance_name,"v1",2,finance),_document("Loan Estimate","v1",3,f"Conventional 30-year fixed estimate lists a loan amount of ${round(price*.80):,.0f}, estimated cash to close, projected principal and interest, estimated taxes and insurance, and lender fee categories. Rate-lock and final cash-to-close figures must be compared with the most current lender and Closing Disclosure records."),
      _document("Seller Property Disclosure","v1",5,"Seller property disclosure is delivered for the identified property. Buyer acknowledgment is present. The disclosure describes the seller's known-condition statements and reminds the buyer that independent inspections and professional advice may be appropriate."),
      _document("Natural Hazard Disclosure","v1",3,"Natural hazard disclosure is delivered and acknowledged for the property. The packet retains the property identity, provider report reference, buyer acknowledgment, and notice that hazard-zone information is not a warranty or substitute for buyer investigation."),
      _document("Preliminary Title Report","v1",7,title),_document("Inspection Report Summary","v1",6,"Licensed home inspection occurred during the inspection period. The retained summary notes routine maintenance observations, recommends ordinary specialist follow-up where desired, and records that no unresolved repair negotiation is represented in this synthetic packet. Buyer acknowledgment is retained."),
      _document("Inspection Contingency Removal","v1",1,"Buyer inspection contingency removal is signed before the recorded deadline. The removal is limited to the inspection contingency and does not waive independently documented title, financing, or disclosure review requirements."),
      _document("Appraisal Notice","v1",2,f"Appraisal notice reflects an appraised value at or above the ${price:,.0f} purchase price for lender underwriting purposes. This retained notice is not an appraisal report and remains subject to the lender's final review and funding conditions."),
      _document("Homeowners Insurance Binder","v1",1,"Insurance binder identifies the property, proposed effective date, carrier, hazard coverage, and lender loss-payee field. Final lender funding remains subject to its own verification of required insurance evidence."),
      _document("Wire Fraud Advisory","v1",1,"Buyer acknowledgement confirms the instruction to verify payment instructions using a trusted, independently obtained phone number. The packet contains no approval for the system, agent, or broker to transmit funds or replace escrow instructions."),
      _document("Final Walk-Through Record","v1",2,"Final walk-through is scheduled close to the anticipated closing date. This retained planning record instructs the buyer-side team to document material property-condition changes or agreed repair items and route them for human review if observed."),
      _document("Agent Visual Inspection Disclosure","v1",2,"Buyer-side and listing-side visual-inspection record is retained for readily observable material conditions. It distinguishes an agent visual review from a professional home, roof, pest, sewer, geological, environmental, or other specialist inspection, and records delivery for buyer review."),
      _document("Seller Property Questionnaire","v1",6,"Seller questionnaire is retained as a separate knowledge-based supplement to the property disclosure. It addresses, to the seller's stated knowledge, repairs, alterations, water intrusion, drainage, neighborhood conditions, utility systems, permits, claims, and other matters that may affect value or desirability."),
      _document("Lead-Based Paint Applicability Notice","v1",1,"Property construction year is recorded as 1988. The pre-1978 lead-based-paint disclosure path is marked not applicable for this synthetic property; a reviewer must re-check the construction year and any later evidence before treating the applicability result as final."),
      _document("Fire Hazard Severity Zone Notice","v1",2,"Fire-hazard severity-zone applicability is screened against the property location and construction-year condition. The demo record reports no triggered additional fire-zone notice, but retains a review prompt for local map, insurance, defensible-space, and seller-notice confirmation when applicable."),
      _document("Mello-Roos and 1915 Act Notice","v1",2,"Special-tax and assessment-district applicability is screened for the identified parcel. The synthetic record reports no known separate Mello-Roos or 1915 Act notice in the packet and directs a reviewer to confirm current tax and assessment information through the appropriate local source."),
      _document("HOA and Common Interest Applicability","v1",2,"The transaction intake identifies no HOA or common-interest development for this synthetic single-family property. If an HOA applies, the workflow requires governing documents, financial and fee information, transfer requirements, assessment information, and buyer review evidence rather than assuming this not-applicable result."),
      _document("Local and Property System Applicability","v1",3,"The retained property profile identifies public water, public sewer, electric, and gas, with no disclosed leased solar equipment. This applicability record flags local transfer, airport, environmental, well, septic, private-road, solar, zoning, and retrofit notices for property-specific confirmation when conditions require them."),
      _document("Pest and Wood-Destroying Organism Report","v1",4,"A synthetic wood-destroying-organism inspection summary is retained for review. It notes no open clearance or treatment requirement in this demo record and states that any actual finding, bid, repair agreement, or clearance request must be preserved as its own source and reviewed by the appropriate parties."),
      _document("Insurance and Flood Evaluation","v1",3,"Homeowners-insurance and flood-review record identifies the need to compare insurer coverage, deductible, hazard limitations, lender conditions, and any flood-zone or separate coverage requirement. The retained synthetic evaluation shows standard homeowners coverage planning and no documented special flood-insurance condition."),
      _document("Lender Conditions List","v1",3,"Lender conditions list tracks income, asset, credit, appraisal, title, insurance, occupancy, identity, and final-document conditions. It separates preliminary preapproval from a clear-to-close, and requires the lender's own confirmation before funds may be released."),
      _document("Estimated Closing Statement","v1",4,"Estimated settlement statement organizes the proposed buyer debits and credits, deposit credit, loan proceeds, title and escrow charges, lender fees, prepaid interest, taxes, insurance, and prorations. It is an estimate only and must be reconciled with the final lender Closing Disclosure and escrow/title figures."),
      _document("Seller Withholding and Vesting Review","v1",2,"Seller-side review record flags vesting, deed-signing authority, payoff, and potential federal or California withholding questions for escrow/title confirmation. It does not provide tax advice, determine an exemption, or replace instructions from the seller, escrow holder, title company, or qualified professional."),
      _document("Possession and Repair Confirmation","v1",2,"Possession is planned under the written purchase agreement and final escrow instructions. The synthetic record notes no separately negotiated repair credit or post-closing possession arrangement; any such agreement must be written, retained, and checked against final settlement and walk-through records."),
      _document("Closing Disclosure Draft","v1",5,"Draft Closing Disclosure is retained for a pre-closing comparison. It identifies the loan terms, projected payments, cash to close, closing costs, prepaid items, escrow account information, and transaction summaries that must be compared against the latest Loan Estimate and lender-issued final disclosure before signing.")]
    return docs+(extra or [])
TRANSACTIONS={
 "48290":_case("48290","48 Redwood Place, Harborfield",760000,"September 15, 2026",_packet(760000,"September 15, 2026","Earnest money receipt confirmed by escrow. Funds reference, receipt date, and amount match the purchase agreement deposit requirement.","Financing Approval","Final lender approval and clear-to-close confirmation are retained. Buyer, property address, loan program, and required insurance evidence match the current transaction record.","Preliminary title report identifies the seller's expected vesting and legal description. No unresolved lien exception requiring transaction escalation is identified in this synthetic report.","Residential purchase agreement identifies Taylor Morgan as buyer and Jamie Ellis as seller for 48 Redwood Place, Harborfield, California, APN 084-221-019. Purchase price $760,000; earnest-money deposit $22,800; conventional financing; buyer and seller signatures present. The agreement includes inspection, appraisal, loan, title, and disclosure review periods and directs written changes to the escrow file.","The parties' signed written amendment confirms that the controlling closing date remains September 15, 2026. No price, party, deposit, financing, or title term is changed. The amendment is retained as the later controlling record for the stated date.")),
 "48291":_case("48291","123 Main Street, Harborfield",850000,"September 17, 2026",_packet(850000,"September 17, 2026","Earnest money receipt remains pending confirmation from escrow. The buyer-side file contains a delivery reference, but the actual received amount, receipt timestamp, and escrow confirmation number have not yet been returned. This is an administrative follow-up item, not evidence that funds are unavailable.","Financing Preapproval","Lender preapproval is retained for the buyer and identified property. The record supports conventional financing and notes ordinary underwriting, appraisal, insurance, and final-document conditions before a clear-to-close may be issued.","Preliminary title report identifies expected vesting and a legal-description match. No unresolved lien exception requiring transaction escalation is identified. Standard exceptions remain subject to normal title and escrow review.","Residential purchase agreement identifies Taylor Morgan as buyer and Jamie Ellis as seller for 123 Main Street, Harborfield, California, APN 084-221-019. Purchase price $850,000; earnest-money deposit $25,500; conventional financing; buyer and seller signatures present. The accepted file lists inspection, appraisal, loan, title, disclosure, walk-through, and closing milestones for administrative tracking.","The parties' signed written amendment changes the controlling closing date to September 17, 2026. No purchase-price, party, deposit, financing, title, or disclosure term is changed. The amendment should be read with the underlying agreement when resolving deadlines.")),
 "48292":_case("48292","77 Juniper Lane, Harborfield",925000,"September 22, 2026",_packet(925000,"September 22, 2026","Earnest money receipt confirmed by escrow. Amount and transaction reference are retained; this confirmation does not cure agreement, title, or price conflicts.","Financing Preapproval","Lender preapproval is retained for a conventional purchase. The record is preliminary and cannot resolve inconsistent contract prices, missing execution, title payoff, or final lender underwriting conditions.","Preliminary title report identifies a recorded lien exception that requires written payoff or release evidence before closing. The retained report does not contain payoff approval, release recording, or escrow confirmation that the exception will be cleared.","Residential purchase agreement identifies Taylor Morgan as buyer and Jamie Ellis as seller for 77 Juniper Lane, Harborfield, California, APN 084-221-019. Purchase price $925,000; earnest-money deposit $27,750; conventional financing; buyer signature present. Seller signature missing. The packet must not treat this agreement as fully executed until the missing execution is resolved.","The retained amendment identifies September 22, 2026 as the intended closing date. It does not resolve the missing seller signature, recorded title lien exception, or any later contradictory purchase-price communication.",[_document("Counteroffer","v1",2,"Counteroffer states purchase price $910,000. No superseding amendment resolves the difference between the $925,000 purchase agreement and this counteroffer. Party acceptance and the controlling-price sequence require human review before a final recommendation.",True)])),
}

# Replace the old one-line fixture summaries with complete, source-authored
# instruments before any agent or API route can access the packet.
for _transaction in TRANSACTIONS.values():
    for _source_document in _transaction["documents"]:
        populate_document(_transaction, _source_document)
        _texts = page_texts(_source_document["blocks"])
        _source_document["pageCount"] = len(_texts)
        _source_document["sourcePages"] = [{"number": index, "text": text} for index, text in enumerate(_texts, 1)]

def get_transaction(case_id):
    item=TRANSACTIONS.get(case_id)
    if not item:return None
    transaction=deepcopy(item)
    for document in transaction["documents"]:
        base=f"/demo-packet/{case_id}/{document['assetSlug']}";document["imageUrl"]=f"{base}.png?v={document['sourceHash'][:10]}";document["pdfUrl"]=f"{base}.pdf?v={document['sourceHash'][:10]}"
        for page in document["sourcePages"]:
            suffix = "" if page["number"] == 1 else f"-p{page['number']}"
            page["imageUrl"] = f"{base}{suffix}.png?v={document['sourceHash'][:10]}"
    return transaction
def list_cases():
    return [{key:value[key] for key in ("id","property","closingDate","side")}|{"documents":len(value["documents"])} for value in TRANSACTIONS.values()]
